spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug